name: DevSecOps Lab Pipeline
on: [push, pull_request]
permissions:
  contents: read      # Needed to checkout the code
  security-events: write # Needed to upload SARIF results
jobs:
  sast-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep Scan
        run: |
          # Use --sarif to output the format GitHub understands
          docker run --rm -v $(pwd):/src semgrep/semgrep semgrep scan --sarif --config auto > semgrep.sarif
      
      - name: Upload to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

  iac-scan:
    name: IaC Scan (Checkov)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra/
          framework: terraform
          output_format: cli,json
          output_file_path: iac-results.json
      - name: Upload IaC Results
        uses: actions/upload-artifact@v4
        with:
          name: iac-report
          path: iac-results.json

  dast-scan:
    name: DAST (OWASP ZAP)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://www.google.com' # Replace with your test URL
          rules_file_name: '.zap/rules.tsv'
          fail_action: false # Don't break the build yet